### ISSUE TITLE
no such file or directory, open '/tmp/artifacts/results.json'

### ISSUE THREAD

**Issue by bewatts** [foo-software/lighthouse-check-orb#3]
essentially my circle config.yml: 
```
version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs: 
    lighthouse-test:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          apiToken: $LIGHTHOUSE_CHECK_API_TOKEN
          urls: $LIGHTHOUSE_CHECK_URL_TOKEN
      - lighthouse-check/validate-status:
          minAccessibilityScore: "50"
          minBestPracticesScore: "50"
          minPerformanceScore: "50"
          minProgressiveWebAppScore: "50"
          minSeoScore: "50"

workflows: 
  test: 
    jobs: 
      - lighthouse-test
  
```

output from circle: 
```
#!/bin/sh -eo pipefail
lighthouse-check-status --verbose \
  --outputDirectory /tmp/artifacts \
  --minAccessibilityScore 50 \
  --minBestPracticesScore 50\
  --minPerformanceScore 50 \
  --minProgressiveWebAppScore 50 \
  --minSeoScore 50
```

```

❌  Something went wrong while attempting to enqueue URLs for Lighthouse. See the error below.

 { Error: ENOENT: no such file or directory, open '/tmp/artifacts/results.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at _default (/usr/local/lib/node_modules/@foo-software/lighthouse-check/dist/validateStatus.js:89:43)
    at init (/usr/local/lib/node_modules/@foo-software/lighthouse-check/dist/bin/lighthouse-check-status.js:64:39)
    at Object.<anonymous> (/usr/local/lib/node_modules/@foo-software/lighthouse-check/dist/bin/lighthouse-check-status.js:87:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/artifacts/results.json' }
```

I also tried to make the directory in a step beforehand, and I get this error. 

```
mkdir: can't create directory '/tmp/artifacts': File exists
```
