### ISSUE TITLE
trying to use extraHeaders, gives error

### ISSUE THREAD

**Issue by danmayer** [foo-software/lighthouse-check-orb#9]
I saw this is supported here: https://github.com/foo-software/lighthouse-check-action/pull/13

but when I tried to use it on circle I get an error:

```
jobs:
  test:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: "https://www.ab.cocm,https://www.abc.com/path"
          emulatedFormFactor: "mobile"
          extraHeaders: '{"Cookie":"batman=bruce.wayne"}'
```

I think looking at the code the orb has just never been setup to pass through this arg... am I reading that right, or is this supposed to work, or am I doing something wrong...

```
# Error calling job: 'test'
# Error calling command: 'lighthouse-check/audit'
# Unexpected argument(s): extraHeaders
```
